/*
Ludo Game Engine
Copyright (C) 2016 TwinDrills

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// This file is included wrapped with defines for DefinePrimitiveType macros.
// The format of the macro is:
//
//		DefinePrimitiveType(MetaClassName, NativeType);

DefinePrimitiveType(VoidType,				void)
DefinePrimitiveType(NullPtrType,			nullptr)
DefinePrimitiveType(BoolType,				bool)
DefinePrimitiveType(IntType,				int)
DefinePrimitiveType(UnsignedIntType,		unsigned int)
DefinePrimitiveType(ShortType,				short)
DefinePrimitiveType(UnsignedShortType,		unsigned short)
DefinePrimitiveType(CharType,				char)
DefinePrimitiveType(UnsignedCharType,		unsigned char)
DefinePrimitiveType(LongType,				long)
DefinePrimitiveType(UnsignedLongType,		unsigned long)
DefinePrimitiveType(LongLongType,			long long)
DefinePrimitiveType(UnsignedLongLongType,	unsigned long long)
DefinePrimitiveType(FloatType,				float)
DefinePrimitiveType(DoubleType,				double)
DefinePrimitiveType(IntPtrType,				intptr)
DefinePrimitiveType(UInt8Type,				uint8)
DefinePrimitiveType(UInt16Type,				uint16)
DefinePrimitiveType(UInt32Type,				uint32)
DefinePrimitiveType(UInt64Type,				uint64)
DefinePrimitiveType(Int8Type,				int8)
DefinePrimitiveType(Int16Type,				int16)
DefinePrimitiveType(Int32Type,				int32)
DefinePrimitiveType(Int64Type,				int64)